### PR TITLE
Support docker

### PR DESCRIPTION
**Pull request by bootjp**
*Issue #, if available:*
None

*Description of changes:*
Added Dockerfile and .dockerignore to make it easy to run using Docker.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sethusrinivasan** [comment]
Thanks for your contributon. With your approach, how do you send command line parameters to docker run ?. Can you give us an example?

you could instead author DockerFile like to one below

FROM python:3

COPY . .
RUN pip install --no-cache-dir -r requirements.txt
ENTRYPOINT [ "python", "migrationtools/documentdb_index_tool.py" ]
CMD ["--help"]

**Comment by bootjp** [comment]
So that's it.
This was an inefficient execution.

```bash
docker run bootjp/amazon-documentdb-tools python migrationtools/documentdb_index_tool.py --show-compatible --dir .
```
Fix it.

**Comment by bootjp** [comment]
@sethusrinivasan Is there anything missing?

**Review by tmcallaghan — CHANGES_REQUESTED** [review]
This PR is no longer functional as repository directory structure has changed. Please update the PR so review can commence.

**Comment by bootjp** [comment]
@tmcallaghan fixed it, Please review again.

**Review by tmcallaghan — CHANGES_REQUESTED** [review]
Still needs changes. This is strictly for the index-tool, the Dockerfile should be in the index-tool directory.

**Comment by bootjp** [comment]
> Still needs changes. This is strictly for the index-tool, the Dockerfile should be in the index-tool directory.

Thank you review.

@tmcallaghan fixed it

**Review by tmcallaghan — CHANGES_REQUESTED** [review]
Need to update Dockerfile as it was moved to the index-tool directory. Specifically the RUN and ENTRYPOINT lines. Please test prior to final PR.

**Comment by bootjp** [comment]
@tmcallaghan 
Sorry, I didn't take the test.
Please review it again.

```
[bootjp@manjaro index-tool]$ (master)
$ docker build -t amazon-documentdb-tools-index-tools .
(..snip..)
[bootjp@manjaro index-tool]$ (master)
$ docker run  amazon-documentdb-tools-index-tools`
```

**Review by tmcallaghan — APPROVED** [review]

**Pull request merged**
