### PR TITLE
document exclude directories

### PR DESCRIPTION
**Pull request by kroney**
*Issue #, if available:*

*Description of changes:*
document excluded-directories option in usage. It is in one of the examples further down, but not on the main description

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by tmcallaghan** [comment]
@kroney can you elaborate on what isn't working for excluded directories? I believe I fixed the issue back on November 22 via https://github.com/awslabs/amazon-documentdb-tools/commit/1e88b7ca50084c25b6fad849b69b6528610e9ea4

**Comment by kroney** [comment]
@tmcallaghan: Sure. I tried to run 
```
python3 compat.py --version 5.0 --directory /my/folder/.../../ --excluded-directories node_modules
```

and it still looked into node_modules:
Screenshot 2024-12-04 at 07 45 36

**Comment by tmcallaghan** [comment]
@kroney can you please repeat your test with a fully qualified directory for node_modules? I fixed this functionality a few weeks ago. If fully qualified works I'll update the readme to call that out.

**Comment by kroney** [comment]
Yes, this works then. I expected it to exclude all directories named node_modules. This would be really helpful

**Comment by tmcallaghan** [comment]
Done via https://github.com/awslabs/amazon-documentdb-tools/commit/ad99339c49d364402965a833ff57cdf595f25b35

**Pull request closed without merging**
